services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "taskcreator"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
